### PR TITLE
Add missing bounds on bytes::BytesVectored

### PR DESCRIPTION
**Pull request by colelawrence**
* Fixes compilation for latest nightly (nightly-2021-12-14)

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
Hey @colelawrence thanks for this pr, I'm aware of this problem, however there is a similar problem in Heph-HTTP which I haven't been able to solve. In another pr I've fixed the rustc version: https://github.com/Thomasdezeeuw/heph/pull/520/commits/aa215c9f64a54eae11aec7fcf6df79be399280c5, from https://github.com/Thomasdezeeuw/heph/pull/520.

If you could fix the problem in heph-http that would be great, but until then I can't update the nightly version.

**Comment by colelawrence** [comment]
We can check it out, thanks!

**Comment by colelawrence** [comment]
Current error on nightly-2021-12-17 during `cargo test` in heph-http is:
```
error[E0478]: lifetime bound not satisfied
  --> http/tests/functional/client.rs:49:48
   |
49 |         let (mut stream, handle) = test_server.accept(|address| {
   |                                                ^^^^^^
```

**Comment by colelawrence** [comment]
I tried some trial-and-error prodding, without much luck 🤷‍♂️ 

The posted error seems to be the only lifetime error left among the crates, so at least I have here included the rest of the boundary changes.

Perhaps in a month or so, we can try the latest nightly and see if there are better errors.

**Pull request closed without merging**
